# codemagic.yaml
workflows:
  ios-app-workflow: # Give your workflow a name
    name: iOS App Workflow # Workflow name shown in Codemagic UI
    instance_type: mac_mini_m1 # Or mac_pro
    max_build_duration: 60 # In minutes
    environment:
      flutter: stable # Or specify a version e.g., 3.10.0
      xcode: latest # Or specify a version e.g., 14.3.1
      cocoapods: default
      # Add other environment variables if needed
      # vars:
      #   MY_VARIABLE: value

    scripts:
      - name: Install Flutter dependencies
        script: |
          cd certificate_app
          flutter packages pub get
      - name: Build iOS app
        script: |
          cd certificate_app
          flutter build ios --release
          # If you have code signing set up, you might use:
          # flutter build ipa --release --export-options-plist=ios/ExportOptions.plist

    artifacts:
      - build/ios/iphoneos/*.app # Adjust path if necessary based on your build output
      # - build/ios/ipa/*.ipa # Uncomment if building an IPA with code signing
