# codemagic.yaml
workflows:
  ios-app-workflow: # Give your workflow a name
    name: iOS App Workflow # Workflow name shown in Codemagic UI
    instance_type: mac_mini_m1 # Or mac_pro
    max_build_duration: 60 # In minutes
    environment:
      flutter: stable # Or specify a version e.g., 3.10.0
      xcode: latest # Or specify a version e.g., 14.3.1
      cocoapods: default
      # Add other environment variables if needed
      # vars:
      #   MY_VARIABLE: value

    scripts:
      - name: Install Flutter dependencies
        script: |
          cd certificate_app
          flutter packages pub get
      - name: Build iOS app
        script: |
          cd certificate_app
          # Build IPA for App Store Connect (TestFlight) distribution.
          # Requires App Store Distribution certificate and provisioning profile configured in Codemagic.
          # See: https://docs.codemagic.io/code-signing-yaml/ios-code-signing/
          # This IPA will be uploaded to App Store Connect (manually or via Codemagic publishing steps)
          # and distributed to testers via the TestFlight app.
          flutter build ipa --release 
          # You might need an ExportOptions.plist for App Store distribution:
          # flutter build ipa --release --export-options-plist=ios/ExportOptionsAppStore.plist 

    artifacts:
      # Path for IPA build artifacts
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM # Include dSYM symbols for crash reporting
